### ISSUE TITLE
Eslint broken with schema-utils 3.x

### ISSUE THREAD

**Issue by n-rodriguez** [webpack-contrib/eslint-webpack-plugin#22]
- Operating System: **ArchLinux**
- Node Version: **14.13.0**
- NPM Version: **6.14.8**
- webpack Version: **4.44.2**
- eslint-webpack-plugin Version: **2.1.0**

### Actual Behavior

When I run Webpack it throws an error :

```sh
nicolas@laptop:~/PROJECTS/CONCERTO/concerto$ bin/webpack
/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

TypeError: (0 , _schemaUtils.default) is not a function
    at getOptions (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/eslint-webpack-plugin/dist/options.js:62:28)
    at new ESLintWebpackPlugin (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/eslint-webpack-plugin/dist/index.js:30:44)
    at Object.<anonymous> (/home/nicolas/PROJECTS/CONCERTO/concerto/config/webpack/development.js:10:38)
    at Module._compile (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/yargs/build/lib/yargs.js:587:13)
    at /home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

### How Do We Reproduce?

Run CI with `schema-utils` 3.x ?

**Comment by evilebottnawi** [comment]
This plugin don't use `schema-utils@3` https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/package.json#L53

**Comment by evilebottnawi** [comment]
Don't use `resolution` or something else

**Comment by n-rodriguez** [comment]
> This plugin don't use `schema-utils@3` https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/package.json#L53

How do I migrate to v3?

**Comment by n-rodriguez** [comment]
> Don't use `resolution` or something else

I don't use it, v3 is automatically picked up

**Comment by n-rodriguez** [comment]
> This plugin don't use `schema-utils@3` https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/package.json#L53

it will

**Comment by n-rodriguez** [comment]
https://github.com/webdeveric/webpack-assets-manifest/issues/96#issuecomment-706696318

**Comment by n-rodriguez** [comment]
how other people do : 

* https://github.com/webpack-contrib/file-loader/commit/60508cf17c2689a8c96d8f56ffc6bbc0ed82d553
* https://github.com/webpack-contrib/url-loader/commit/20c744b121bbca006320e7f65c0c65ccb06982ad

**Comment by evilebottnawi** [comment]
Feel free to send PR
