### ISSUE TITLE
Fails with webpack 5 beta 9

### ISSUE THREAD

**Issue by thasmo** [webpack-contrib/eslint-webpack-plugin#3]
- Operating System: Windows 10
- Node Version: 10.16.3
- NPM Version: 6.13.2
- webpack Version: 5-beta.9
- eslint-webpack-plugin Version: 0.0.1

### Expected Behavior
Runs.

### Actual Behavior
Doesn't run.
```
TypeError: Cannot read property 'get' of undefined
    at hasFileChanged (C:\Users\username\Projects\projectname\node_modules\eslint-webpack-plugin\dist\LintDirtyModulesPlugin.js:47:49)
    at LintDirtyModulesPlugin.getChangedFiles (C:\Users\username\Projects\projectname\node_modules\eslint-webpack-plugin\dist\LintDirtyModulesPlugin.js:54:11)
    at LintDirtyModulesPlugin.apply (C:\Users\username\Projects\projectname\node_modules\eslint-webpack-plugin\dist\LintDirtyModulesPlugin.js:34:31)
    at compiler.hooks.watchRun.tapAsync (C:\Users\username\Projects\projectname\node_modules\eslint-webpack-plugin\dist\index.js:39:19)
    at Hook.eval [as callAsync] (eval at create (C:\Users\username\Projects\projectname\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:30:1)
    at compiler.cache.endIdle.err (C:\Users\username\Projects\projectname\node_modules\webpack\lib\Watching.js:65:33)
    at C:\Users\username\Projects\projectname\node_modules\webpack\lib\HookWebpackError.js:69:3
    at Hook.eval [as callAsync] (eval at create (C:\Users\username\Projects\projectname\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.endIdle (C:\Users\username\Projects\projectname\node_modules\webpack\lib\Cache.js:140:22)
    at Watching._go (C:\Users\username\Projects\projectname\node_modules\webpack\lib\Watching.js:63:23)
    at Watching._invalidate (C:\Users\username\Projects\projectname\node_modules\webpack\lib\Watching.js:238:9)
    at watcher.compiler.watchFileSystem.watch (C:\Users\username\Projects\projectname\node_modules\webpack\lib\Watching.js:202:11)
    at Watchpack.watcher.once (C:\Users\username\Projects\projectname\node_modules\webpack\lib\node\NodeWatchFileSystem.js:85:4)
    at Object.onceWrapper (events.js:286:20)
    at Watchpack.emit (events.js:198:13)
    at Watchpack.EventEmitter.emit (domain.js:448:20)
```

**Comment by ricardogobbosouza** [comment]
Hi @thasmo Sorry for the delay.

Added support for webpack 5 beta on [v0.1.0](https://github.com/webpack-contrib/eslint-webpack-plugin/releases/tag/v0.1.0)
